name: Valeria Micol Garcia
description: Computer Engineering Student at UNLP | AI & Machine Learning Enthusiast
avatar: /images/valeria_profile.jpg # Guardá tu foto del CV con este nombre en la carpeta images

# Navegación superior (Sin Publications)
navigation:
  - name: ABOUT
    url: "#about"
  - name: CAREER
    url: "#career"
  - name: BLOG
    url: /blog

# Enlaces de contacto y redes
footer-links:
  github: valemicolgarcia
  linkedin: valeria-micol-garcia-72a653267
  email: valemicolgarcia@gmail.com

# Jekyll settings
source: .
destination: _site
paginate: 5

# GitHub Pages settings
url: https://valemicolgarcia.github.io
baseurl: ""