services:
  - type: web
    name: stress-detection-api
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel cython numpy && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
